[package]
name = "caderno"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.29"
egui = "0.29"
egui_commonmark = "0.18"
egui_extras = { version = "0.29", features = ["all_loaders"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_yaml = "0.9"
dirs = "5"
chrono = { version = "0.4", features = ["serde"] }
meval = "0.2"
uuid = { version = "1", features = ["v4"] }
rfd = "0.15"
walkdir = "2"
notify = "6"
slug = "0.1"
pulldown-cmark = "0.12"
lopdf = "0.34"
zip = { version = "2", default-features = false, features = ["deflate"] }

[profile.release]
opt-level = 3
lto = true
strip = true
