use serde::{Deserialize, Serialize};
use std::path::PathBuf;

#[derive(Clone, Copy, Debug, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "lowercase")]
#[derive(Default)]
pub enum NoteType {
    #[default]
    Resumo,
    Citacao,
    Codigo,
    Exercicio,
    Duvida,
    Definicao,
}

impl NoteType {
    pub fn label(&self) -> &'static str {
        match self {
            Self::Resumo => "Resumo",
            Self::Citacao => "Citação",
            Self::Codigo => "Código",
            Self::Exercicio => "Exercício",
            Self::Duvida => "Dúvida",
            Self::Definicao => "Definição",
        }
    }
    pub fn icon(&self) -> &'static str {
        match self {
            Self::Resumo => "📄",
            Self::Citacao => "💬",
            Self::Codigo => "💻",
            Self::Exercicio => "✏",
            Self::Duvida => "❓",
            Self::Definicao => "💡",
        }
    }
    pub fn all() -> [NoteType; 6] {
        [
            Self::Resumo,
            Self::Citacao,
            Self::Codigo,
            Self::Exercicio,
            Self::Duvida,
            Self::Definicao,
        ]
    }
}

#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct Frontmatter {
    pub id: String,
    #[serde(rename = "type", default)]
    pub note_type: NoteType,
    #[serde(default)]
    pub tags: Vec<String>,
    #[serde(default)]
    pub source: String,
    #[serde(default)]
    pub source_link: String,
    #[serde(default)]
    pub linked_note: Option<String>,
    #[serde(default)]
    pub attachments: Vec<String>,
    #[serde(default)]
    pub created: String,
    /// Obsidian-compatible aliases. A `[[link]]` whose target matches any alias
    /// resolves to this note. CAD-20 (Phase 1 link parity).
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub aliases: Vec<String>,
    /// One-line summary generated by `omninote tag --auto`. CAD-23.2.
    /// Omitted from serialization when empty so existing notes stay clean.
    #[serde(default, skip_serializing_if = "String::is_empty")]
    pub summary: String,
}

#[derive(Clone, Debug)]
pub struct Note {
    pub path: PathBuf,
    pub rel_path: PathBuf,
    pub frontmatter: Frontmatter,
    pub title: String,
    pub content: String,
}

#[derive(Clone, Copy, Debug, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "lowercase")]
#[derive(Default)]
pub enum FontFamily {
    #[default]
    System,
    Monospace,
    Serif,
}

impl FontFamily {
    pub fn label(&self) -> &'static str {
        match self {
            Self::System => "Sistema (sans-serif)",
            Self::Monospace => "Monospace",
            Self::Serif => "Serif",
        }
    }
    pub fn all() -> [FontFamily; 3] {
        [Self::System, Self::Monospace, Self::Serif]
    }
    // CAD-21: `as_egui_family()` moved to `omninote-gui::theme::font_family_to_egui`
    // to keep `omninote-core` free of UI dependencies.
}

fn default_font_size() -> f32 {
    14.0
}
fn default_line_height() -> f32 {
    1.4
}
fn default_letter_spacing() -> f32 {
    0.0
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct AppConfig {
    #[serde(default)]
    pub dark_mode: bool,
    #[serde(default)]
    pub last_active: Option<String>,
    #[serde(default)]
    pub recent_vaults: Vec<PathBuf>,
    #[serde(default)]
    pub font_family: FontFamily,
    #[serde(default = "default_font_size")]
    pub font_size: f32,
    #[serde(default = "default_line_height")]
    pub line_height: f32,
    #[serde(default = "default_letter_spacing")]
    pub letter_spacing: f32,
}

impl Default for AppConfig {
    fn default() -> Self {
        Self {
            dark_mode: false,
            last_active: None,
            recent_vaults: Vec::new(),
            font_family: FontFamily::default(),
            font_size: default_font_size(),
            line_height: default_line_height(),
            letter_spacing: default_letter_spacing(),
        }
    }
}

#[derive(Clone, Debug)]
pub enum ConfirmAction {
    DeleteNote(String),
    DeleteFolder(PathBuf),
}
