use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;
use std::path::PathBuf;

#[derive(Clone, Copy, Debug, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "lowercase")]
#[derive(Default)]
pub enum NoteType {
    #[default]
    Resumo,
    Citacao,
    Codigo,
    Exercicio,
    Duvida,
    Definicao,
}

impl NoteType {
    pub fn label(&self) -> &'static str {
        match self {
            Self::Resumo => "Resumo",
            Self::Citacao => "Citação",
            Self::Codigo => "Código",
            Self::Exercicio => "Exercício",
            Self::Duvida => "Dúvida",
            Self::Definicao => "Definição",
        }
    }
    pub fn icon(&self) -> &'static str {
        match self {
            Self::Resumo => "📄",
            Self::Citacao => "💬",
            Self::Codigo => "💻",
            Self::Exercicio => "✏",
            Self::Duvida => "❓",
            Self::Definicao => "💡",
        }
    }
    pub fn all() -> [NoteType; 6] {
        [
            Self::Resumo,
            Self::Citacao,
            Self::Codigo,
            Self::Exercicio,
            Self::Duvida,
            Self::Definicao,
        ]
    }
}

#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct Frontmatter {
    pub id: String,
    #[serde(rename = "type", default)]
    pub note_type: NoteType,
    #[serde(default)]
    pub tags: Vec<String>,
    #[serde(default)]
    pub source: String,
    #[serde(default)]
    pub source_link: String,
    #[serde(default)]
    pub linked_note: Option<String>,
    #[serde(default)]
    pub attachments: Vec<String>,
    #[serde(default)]
    pub created: String,
    /// Obsidian-compatible aliases. A `[[link]]` whose target matches any alias
    /// resolves to this note. CAD-20 (Phase 1 link parity).
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub aliases: Vec<String>,
    /// One-line summary generated by `omninote tag --auto`. CAD-23.2.
    /// Omitted from serialization when empty so existing notes stay clean.
    #[serde(default, skip_serializing_if = "String::is_empty")]
    pub summary: String,
    /// Unknown frontmatter keys — Obsidian custom fields (`cssclass`, `publish`,
    /// `cover`, Dataview inline fields, …) that OmniNote does not model. Preserved
    /// across a parse → save round-trip: `parse_frontmatter` extracts them here via
    /// a tolerant `Mapping` pass (`frontmatter_from_yaml` — a strict deserialize
    /// would fail on a foreign note and drop the whole frontmatter), and `flatten`
    /// splices them back inline on serialize (no `extra:` wrapper). `BTreeMap` keeps
    /// key order deterministic for stable git diffs on a versioned vault. Caveat: an
    /// unknown `type:` value normalizes to the default — a modeled `type` key can't
    /// coexist with a foreign one on save — but every other key survives. CAD-25b.
    #[serde(flatten, default)]
    pub extra: BTreeMap<String, serde_yaml::Value>,
}

#[derive(Clone, Debug)]
pub struct Note {
    pub path: PathBuf,
    pub rel_path: PathBuf,
    pub frontmatter: Frontmatter,
    pub title: String,
    pub content: String,
}

#[derive(Clone, Copy, Debug, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "lowercase")]
#[derive(Default)]
pub enum FontFamily {
    #[default]
    System,
    Monospace,
    Serif,
    /// OpenDyslexic — open-source typeface for dyslexic readers. The egui font
    /// registration lives in the gui crate; core only carries the variant.
    Dyslexic,
}

impl FontFamily {
    pub fn label(&self) -> &'static str {
        match self {
            Self::System => "Sistema (sans-serif)",
            Self::Monospace => "Monospace",
            Self::Serif => "Serif",
            Self::Dyslexic => "OpenDyslexic (dislexia)",
        }
    }
    pub fn all() -> [FontFamily; 4] {
        [Self::System, Self::Monospace, Self::Serif, Self::Dyslexic]
    }
    // `as_egui_family()` moved to `omninote-gui::theme::font_family_to_egui`
    // to keep `omninote-core` free of UI dependencies.
}

fn default_font_size() -> f32 {
    14.0
}
fn default_line_height() -> f32 {
    1.4
}
fn default_letter_spacing() -> f32 {
    0.0
}

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct AppConfig {
    #[serde(default)]
    pub dark_mode: bool,
    #[serde(default)]
    pub last_active: Option<String>,
    #[serde(default)]
    pub recent_vaults: Vec<PathBuf>,
    #[serde(default)]
    pub font_family: FontFamily,
    #[serde(default = "default_font_size")]
    pub font_size: f32,
    #[serde(default = "default_line_height")]
    pub line_height: f32,
    #[serde(default = "default_letter_spacing")]
    pub letter_spacing: f32,

    // UI v2 (CAD-25 Fase B) — all serde-default for backwards-compat with v1.0 config.json.
    #[serde(default = "default_true")]
    pub right_rail_open: bool,
    #[serde(default)]
    pub right_rail_tab: RightRailTab,
    #[serde(default)]
    pub daily_auto_open: bool,
    #[serde(default)]
    pub default_template_for_daily: Option<String>,
    /// Provider name as a string ("claude"/"grok"/"ollama"/"disabled") — kept a
    /// string so `omninote-core` stays free of an `omninote-ai` dependency.
    /// Empty by default = AI disabled until the user configures it (fail-safe).
    #[serde(default)]
    pub llm_provider: String,
    #[serde(default = "default_llm_model")]
    pub llm_model_id: String,
    #[serde(default = "default_accent")]
    pub accent_color: [u8; 3],
    #[serde(default)]
    pub theme_preset: ThemePreset,
    #[serde(default = "default_capture_hotkey")]
    pub quick_capture_hotkey: String,
    #[serde(default = "default_dictation_hotkey")]
    pub dictation_hotkey: String,
    #[serde(default = "default_dictation_locale")]
    pub dictation_locale: String,
    #[serde(default = "default_palette_hotkey")]
    pub palette_hotkey: String,
}

/// Theme variant selected in settings. Maps to a gui-side `Theme` (egui colors).
/// `lowercase` wire format matches the sibling `FontFamily`/`NoteType` enums.
///
/// The first 4 variants shipped first (Slice 1) — their wire names are load-bearing
/// for existing `.omninote/config.json` files, so new variants are appended after
/// `Custom` rather than reordered/renamed. `AlmanacLight`/`AlmanacDark`/`Blueprint`/
/// `BlueprintLight`/`Swiss` recover the palettes built in the `cortex/off-{1,2}`
/// design experiments and the `omninote-swiss-theme` stash (see `omninote-gui`'s
/// `theme.rs` for the concrete `Color32` values and provenance doc comments).
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum ThemePreset {
    #[default]
    ObsidianDark,
    ObsidianLight,
    HighContrast,
    Custom,
    AlmanacLight,
    AlmanacDark,
    Blueprint,
    BlueprintLight,
    Swiss,
}

impl ThemePreset {
    pub fn label(&self) -> &'static str {
        match self {
            Self::ObsidianDark => "Terminal Escuro",
            Self::ObsidianLight => "Terminal Claro",
            Self::HighContrast => "Alto Contraste",
            Self::Custom => "Personalizado",
            Self::AlmanacLight => "Almanac",
            Self::AlmanacDark => "Almanac Noite",
            Self::Blueprint => "Blueprint",
            Self::BlueprintLight => "Blueprint Rascunho",
            Self::Swiss => "Swiss",
        }
    }
    pub fn all() -> [ThemePreset; 9] {
        [
            Self::ObsidianDark,
            Self::ObsidianLight,
            Self::AlmanacLight,
            Self::AlmanacDark,
            Self::Blueprint,
            Self::BlueprintLight,
            Self::Swiss,
            Self::HighContrast,
            Self::Custom,
        ]
    }
}

/// Active tab in the right rail (320px panel).
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum RightRailTab {
    #[default]
    Backlinks,
    Outline,
    AiChat,
}

fn default_true() -> bool {
    true
}
fn default_llm_model() -> String {
    "claude-3-5-sonnet-latest".to_string()
}
fn default_accent() -> [u8; 3] {
    [0x8b, 0x7c, 0xff]
}
fn default_capture_hotkey() -> String {
    "Ctrl+Shift+Space".to_string()
}
fn default_dictation_hotkey() -> String {
    "Ctrl+Shift+M".to_string()
}
fn default_dictation_locale() -> String {
    "pt-BR".to_string()
}
fn default_palette_hotkey() -> String {
    "Ctrl+P".to_string()
}

impl Default for AppConfig {
    fn default() -> Self {
        Self {
            dark_mode: false,
            last_active: None,
            recent_vaults: Vec::new(),
            font_family: FontFamily::default(),
            font_size: default_font_size(),
            line_height: default_line_height(),
            letter_spacing: default_letter_spacing(),
            right_rail_open: true,
            right_rail_tab: RightRailTab::default(),
            daily_auto_open: false,
            default_template_for_daily: None,
            llm_provider: String::new(),
            llm_model_id: default_llm_model(),
            accent_color: default_accent(),
            theme_preset: ThemePreset::default(),
            quick_capture_hotkey: default_capture_hotkey(),
            dictation_hotkey: default_dictation_hotkey(),
            dictation_locale: default_dictation_locale(),
            palette_hotkey: default_palette_hotkey(),
        }
    }
}

#[derive(Clone, Debug)]
pub enum ConfirmAction {
    DeleteNote(String),
    DeleteFolder(PathBuf),
}
